name: Update README with Stats

on:
  push:
    branches:
      - main   # or master if your default branch is master
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update README
        uses: wow-actions/write-in-readme@v1
        with:
          files: README.md
          pattern: "<!--START_SECTION:github_stats-->[\\s\\S]*<!--END_SECTION:github_stats-->"
          value: |
            ![Shafia Ameeruddin's GitHub Stats](https://github-readme-stats.vercel.app/api?username=Shafia-01&count_private=true&show_icons=true&theme=radical&cache_seconds=1800)

            ![Most Used Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=Shafia-01&layout=compact&theme=radical&cache_seconds=1800)

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Updated README with latest GitHub Stats"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

